### ISSUE TITLE
vq_test_unannotated.json seems to be missing

### ISSUE THREAD

**Issue by artest08** [EGO4D/episodic-memory#15]
python convert_videos_to_clips.py \
    --annot-paths data/vq_val.json data/vq_test_unannotated.json \
    --save-root data/clips \
    --ego4d-videos-root $EGO4D_VIDEOS_DIR \
    --num-workers 10 # Increase this for speed

The commands above requires the json file which seems to be missing currently in my case.

**Comment by miguelmartin75** [comment]
The unannotated test JSONs are coming, but are not currently available.

**Comment by ebyrne** [comment]
The annotations are now available, apologies on the delay.  Please update via the CLI (https://github.com/facebookresearch/Ego4d/tree/main/ego4d/cli#readme) and let us know if you have any questions.
