### ISSUE TITLE
Video to Image conversion (no valid frame for specific sample)

### ISSUE THREAD

**Issue by artest08** [EGO4D/episodic-memory#16]
For the VQ2D task, during the conversion from video to image with the command below:
python convert_videos_to_images.py \
    --annot-paths data/vq_train.json data/vq_val.json \
    --save-root data/images \
    --ego4d-videos-root $EGO4D_VIDEOS_DIR \
    --num-workers 10 # Increase this for speed

I get the error "No valid frames to read for" for the samples below:
4f11d6b8-1f78-4d99-9b34-7b89bc007b25
28ff9118-e876-497c-9901-cb89a62509fc
f4faa012-2e68-4f51-b054-27deaff4204c
e93fdf27-c14c-4794-b4b7-20685b40156f
b1faab00-8666-40e4-8038-c9060e83e6cd
a8175d36-481a-4c4d-9928-f1d31cb2254b
bf7c866e-4623-420c-af44-b9ff5c2fa66c
01111831-9107-43c4-bf0e-6b26e9b32a2b
0a3097fc-baed-4d11-a4c9-30f07eb91af6
609d9772-daa2-45e9-b07a-1ffdadb942b4
111ee12a-6af2-4bfc-8586-e706568fd078
339442c2-7d71-4c1e-821c-b955bdd31f44
0d2231f9-d67a-4df0-b36f-40cbf374ed03
60f4b15e-b23e-4c7f-9cb3-f51ac164bb23
407216c9-b0f1-4fe1-af09-9405a7657953
8f693e8a-5ea4-4b0f-93fd-787fe5f481df
d4c28488-a494-405d-bc8d-27a074aa9c5c

Is this related with my download problem or is there anyone who gets the same error?

Thanx in advance

**Comment by hskAlena** [comment]
I cannot remember specific video names, but I did have the same error!
Though, I've only downloaded clips and changed the python file to convert clips to images.

**Comment by srama2512** [comment]
@artest08  - It looks like these are videos for which no annotations were included. For example, when I retrieve the video annotations for a couple of the above video uids:
```
[{'video_uid': '4f11d6b8-1f78-4d99-9b34-7b89bc007b25',
  'split': 'train',
  'clips': []}]

{'video_uid': '28ff9118-e876-497c-9901-cb89a62509fc',
 'split': 'train',
 'clips': []}
```

In these cases, the script ignores the videos to avoid erroring out later. It is not necessarily an error. 
https://github.com/EGO4D/episodic-memory/blob/94d62779c01b2598b3acd13904225a20a0f45c08/VQ2D/convert_videos_to_images.py#L126-L128
