### ISSUE TITLE
Clips in VQ2D annotation seem to be different from benchmark clips.

### ISSUE THREAD

**Issue by hskAlena** [EGO4D/episodic-memory#17]
Hello!
I've checked val_annot.json.gz in vq2d and I found out 'video_frame_number' and '(clip)frame_number' point to other frames, shown in the first image. 
But when I used extracted clips from full_scale videos (using convert_videos_to_clips.py), not benchmark clips I downloaded directly from Ego4D, it seems to return frames within the same range, as in the second image.

Is this right? The benchmark clips are not for VQ2D annotations? 

![image](https://user-images.githubusercontent.com/52067195/163676168-a232bf92-479b-4202-ad24-9ef289f89a3c.png)

![image](https://user-images.githubusercontent.com/52067195/163676543-cf6d8afe-4ea5-4dba-9e02-578e8b80033d.png)

**Comment by srama2512** [comment]
@hskAlena  - The benchmark clips are likely at a different frame rate than is required for VQ2D (which needs 5 FPS). The `convert_videos_to_clips.py` accounts for the frame rate changes. You could modify the script to process clips instead of videos to get the VQ2D 5 FPS clips.

**Comment by srama2512** [comment]
@hskAlena - can we close this issue? Did the above response address your question?

**Comment by hskAlena** [comment]
Yes! The frame rates are different. Thanks for the answer!
