### ISSUE TITLE
VQ2D evaluation on validation split takes 70+ hours

### ISSUE THREAD

**Issue by fcakyon** [EGO4D/episodic-memory#18]
Hello I am using the [VQ2D evaluation script](https://github.com/EGO4D/episodic-memory/blob/main/VQ2D/scripts/evaluate_vq.sh) with default config params (siam_rcnn_residual+kys, data.split="val", data.num_processes=2) on a A100 gpu but it takes 70+ hours. 

Is this expected?

Some clikp eval durations:

```bash
====> Data uid: val_0000000074 | search window :     411 frames | clip read time:   0.01 mins | detection time:   0.51 mins | peak signal time:   0.00 mins | tracking time:   5.03 mins
```

```bash
====> Data uid: val_0000000075 | search window :     251 frames | clip read time:   0.02 mins | detection time:   0.31 mins | peak signal time:   0.00 mins | tracking time:   0.63 mins
```

```bash
====> Data uid: val_0000000076 | search window :     522 frames | clip read time:   0.01 mins | detection time:   0.65 mins | peak signal time:   0.00 mins | tracking time:   0.82 mins
```

```bash
====> Data uid: val_0000000065 | search window :    1230 frames | clip read time:   0.01 mins | detection time:   1.64 mins | peak signal time:   0.00 mins | tracking time:  16.46 mins
```

**Comment by srama2512** [comment]
@fcakyon  - Yes, this is expected. For the Ego4D experiments, we split the vq2d validation split into 20 different parts and evaluated them parallelly to speed things up.

**Comment by srama2512** [comment]
Closing issue since it has been addressed. Please feel free to open it if there are further questions.
