### ISSUE TITLE
VQ2D val set visualizations are exported for only 12 clips 

### ISSUE THREAD

**Issue by fcakyon** [EGO4D/episodic-memory#19]
When I run the evaluation script with default params, there are `example_{x}_graph.png`, `example_{x}_rt.mp4`, `example_{x}_sw.mp4` visuals exported for `x=[0 to 11]` (note  that process number=12). 

How can I make it export visuals for all clips instead of the latest 12 clip? Current implementation overrides the exported visuals for some reason.

**Comment by srama2512** [comment]
@fcakyon  - The visualization was intended to only run with 1 process. If you'd like to run it with multiple processes, you can change `example_{idx:05d}_*` to `example_{annotation["dataset_uid"]}_*` (or pass the process index and use that in the naming).
