### ISSUE TITLE
MQ missing annotation files for the baseline

### ISSUE THREAD

**Issue by JunweiLiang** [EGO4D/episodic-memory#27]
Hi,

for the MQ baseline, there are files like `clip_annotations.json` and `moment_classes_idx.json` (from this [code](https://github.com/EGO4D/episodic-memory/blob/main/MQ/Utils/opts.py#L30)) that are missing from the repo (and I could not find them in the official dataset). Could you provide them or a way to generate them? Thanks!

Best,
Junwei

**Comment by Chief-Buka** [comment]
I believe the `moment_classes_idx.json` is created (upon training) in the specified path if it doesn't exist already exist. It is in `_getDatasetDict()` method in `episodic-memory/MQ/Utils/dataset.py`

**Comment by JunweiLiang** [comment]
The `clip_annotations.json` is the keep missing part. I guess we could generate it ourselves if the differences to the `moments_*.json` files are just on the dict names.

**Comment by Wangjh0125** [comment]
Hi, I have met the same problem. Could you please tell me how do you get the clip_annotations.json file? Thank you.

**Comment by JunweiLiang** [comment]
@Wangjh0125 The updated code will generate that file now.
