### ISSUE TITLE
NLQ task 2D-TAN yaml file missing

### ISSUE THREAD

**Issue by YangtaoWANG95** [EGO4D/episodic-memory#5]
Hi, 

Thank you for this wonderful work. For NLQ task baseline 2D-TAN, I can't find the configuration file experiments/ego4d/2D-TAN-40x40-K9L4-pool-window-std-sf.yaml. Is it the same as one of the yaml files for another dataset?

**Comment by miguelmartin75** [comment]
I believe so, @satwikkottur  can confirm.

**Comment by frostinassiky** [comment]
@YangtaoWANG95 Thanks for the feedback. I will upload this file.

**Comment by NNNNAI** [comment]
Hi, thanks for sharing your wonderful work. But the " experiments/ego4d/2D-TAN-40x40-K9L4-pool-window-std-sf.yaml" is still missing now. Will it be uploaded?

**Comment by frostinassiky** [comment]
Yes it will :) @NNNNAI

**Comment by frostinassiky** [comment]
#13
